application: cozyonboard
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- channel_presence

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images 

- url: /.*
  script: onboard.application


libraries:
- name: webapp2
  version: latest
- name: jinja2 
  version: latest
