#!/bin/bash


ONBOARD_NODE_MODULES=$1
ONBOARD_WLAN_DEVICE=$2
ONBOARD_DEVICE_ID=$3
ONBOARD_VENDOR_ID=$4

exec sudo \
	ONBOARD_NODE_MODULES=$ONBOARD_NODE_MODULES \
	ONBOARD_WLAN_DEVICE=$ONBOARD_WLAN_DEVICE \
	ONBOARD_DEVICE_ID=$ONBOARD_DEVICE_ID \
	ONBOARD_VENDOR_ID=$ONBOARD_VENDOR_ID \
	BLENO_HCI_DEVICE_ID=0 \
	DEBUG=* \
	node onboarding.js
